export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const INCREASE_POMODORO = 'INCREASE_POMODORO';
export const DECREASE_POMODORO = 'DECREASE_POMODORO';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_EDIT_TASK = 'SET_EDIT_TASK';